### ISSUE TITLE
No new devices have been found.

### ISSUE THREAD

**Issue by klim123123** [MadMonkey87/HomeyCONZ#12]
Trying to add "TRÅDFRI open/close switch" as "Tradfri Square Dimmer".
 I'm always see: No new devices have been found.
To test deCONZ settings, i was able to add light bulb. But when i add switch, i always see  No new devices have been found.
Please help.

            "ep": 1,
            "etag": "344a283de01e40746ff2e31021864a09",
            "lastseen": "2020-06-16T12:33:41.263",
            "manufacturername": "IKEA of Sweden",
            "mode": 1,
            "modelid": "TRADFRI open/close remote",
            "name": "TRADFRI open/close remote ",
            "state": {
                "buttonevent": null,
                "lastupdated": "none"
            },
            "swversion": "2.2.010",
            "type": "ZHASwitch",
            "uniqueid": "00:0d:6f:ff:fe:9a:9a:f5-01-1000"

P.S
I was able to add "TRÅDFRI open/close switch" as "Generic Wireless Switch",
but not "Tradfri Square Dimmer"

P.S.S.
Looks like it's different devices from IKEA, but looks very very similar.
"TRÅDFRI open/close switch" comes with IKEA blinds.
Is it possible to ask you to add this device?

P.S.S.
I tried to use it as "Generic Wireless Switch", but all i get is
release_after_press
release_after_hold
actions. and i get them 8x time each time i press and release.

**Comment by MadMonkey87** [comment]
Sure, I'll supportthis one too;) Looks like it is indeed very similar, I'll simply extend the square dimmer driver

**Comment by MadMonkey87** [comment]
New version is ready for testing. Can you please install it from here and confirm if it now works?

https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

**Comment by klim123123** [comment]
Thank you. But two problems:
Dim Down Single Press - works
Dim Up Single Press- works
Dim Down Released - works
Dim Up Released - works
Dim Down Held - doesn't work
Dim Up Held - doesn't work

**Comment by MadMonkey87** [comment]
Glad to see it works in general. According to https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices the device only supports single press and released, held is not supported. I remove this option from the app
