### ISSUE TITLE
Zipato smart water leakage sensor

### ISSUE THREAD

**Issue by marindal** [MadMonkey87/HomeyCONZ#15]
**Device name:**
 Zipato Smart Water Leakage sensor

**Device link:**
https://www.zipato.com/product/flood-sensor-zigbee

**Device modelid:**
HM-HS1WL-M

**Device capabilities:**
Water leakage

**State report example:**

Vendor
Zipato
Product
WATER_CTPG
Version2017.4.18
Battery
100
 %
Battery
state ok
Water
none
Refreshed
07/02/2020 5:43:37 PM
![zipato](https://user-images.githubusercontent.com/43535441/86389072-1617db80-bc96-11ea-85f5-7c42e6cb9521.PNG)
}
Read more here: https://dresden-elektronik.github.io/deconz-rest-doc/websocket/
--->

**Comment by MadMonkey87** [comment]
Hey @marindal 
I try to support this device with the next release, can you please post the json of the rest api of this device?

**Comment by MadMonkey87** [comment]
I implemented a draft with the 1.10 release, but I am not sure if it really works, please test it and let me know if something is wrong or if it's all fine

**Comment by marindal** [comment]
Hi MM :) 

Sorry, forgot this one :)
Back in the game... and still have som issues regarding this sensor... 
I Can include it within my deConz installstallation, but I cannot add it to Homey....

Included a Philips Hue lamp for testing, and it worked fine with Homey.

BR 
Marius
