### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bhelbers** [MadMonkey87/HomeyCONZ#16]
**Describe the bug:**
Tradfri bulb CWS: changing color does not work

**How to reproduce:**
Select the device and try to change the color

**How it should work:**
Use xy instead of hue and saturation or use xy in addition to hue and saturation (the latter is what the Phoscon app does) so for a PUT /api/<apikey>/lights/<id>/state use e.g.
{"xy":[0.7328473782062022,0.26597735316344395]} or
{"hue":196,"sat":252,"xy":[0.7328473782062022,0.26597735316344395]}
instead of
{"hue":196,"sat":252}

**Additional context:**
Apparently this bulb only supports xy for setting the color despite the fact that (some older firmware versions at least) report otherwise.
Tested with lamp firmwares 1.3.002 and 1.3.013, deconz 2.05.77 and conbee ii with firmware 0x264a0700

**Comment by MadMonkey87** [comment]
I need to investigate that case a little deeper, could be a litte tricky to resolve;)

**Comment by MadMonkey87** [comment]
Just s.t I can implement model specific changes, can you please provide me the resource of your light provided by the api?

**Comment by bhelbers** [comment]
Is this what you’re looking for?

{
    "ctmax":454,
    "ctmin":250,
    "etag":"1b4dd51026e326dfb544ec4268ae7e47",
    "hascolor":true,
    "lastseen":"2020-07-06T12:30:15.340",
    "manufacturername":"IKEA of Sweden",
    "modelid":"TRADFRI bulb E27 CWS opal 600lm",
    "name":"Color light 4",
    "state":
    {
        "alert":"none",
        "bri":2,
        "colormode":"xy",
        "effect":"none",
        "hue":0,
        "on":false,
        "reachable":true,
        "sat":254,
        "xy":[0.7313,0.2678]
    },
    "swversion":"1.3.013",
    "type":"Color light",
    "uniqueid":"d0:cf:5e:ff:fe:29:59:2a-01"
}

**Comment by MadMonkey87** [comment]
Yes thx! As this is hightly specific to that device (and kind of a bug in the firmware of this device) I'll try to implement it like that:
1) in general provide a setting where every light can be configured to operate in the hue & sat mode or in the xy mode
2) by default all lights will use the hue & sat mode, but for your specific device this setting will be preset to xy

**Comment by MadMonkey87** [comment]
Just as with Phoscon, also Homey works with colors using hue and saturation. So in order to make your device work properly I need to convert hue and sat to xy and back what does not seem to be trivial. How did you calculate xy in your example?

**Comment by bhelbers** [comment]
I captured some API traffic from both homey-conz and the phoscon app and noticed that the phoscon app calls always contain both hue/sat as well as xy. I did not calculate the xy values just copy them from the captured packets instead.

**Comment by MadMonkey87** [comment]
I've pushed a preprelease for this case. Please install it from https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/ and let me know if it works. 

Important: you need to go to the settings of your bulb and enable the newly introduced xy mode!

**Comment by bhelbers** [comment]
Installed the prerelease and enabled xy mode. tested using manual control from the homey app. Here is what I noticed:
- on/off and dimming works as expected
- Using the color wheel the color can be changed to any color except red. Instead of changing to read an error message “timed out after 30000ms” appears on the top of the screen after approx 30 seconds. Network trace also shows no http request is made to deconz when trying to change to red.
- Using the color wheel the color can only be changed to from coloror white to white but only to a few warmth variants that are all in the middle. The extreme cold and warm ones do not work. I do see the http requests. In the color control (0300) cluster info of the lamp it says color temp min = 250 and color temp max=454. The ones that do not work have values outside this range so I guess that is the cause.
- When changing the color using xy mode transition time is included in the json but always set to 0, regardless of what I configure for the lamp (i’ve tried values 4, 5 and 100)
- When changing from color to white or changing the warmth of white only ct is in the json.
