### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by marindal** [MadMonkey87/HomeyCONZ#18]
**Describe the bug:**
When trying to add the Zipato Leakage sensor, I get «No new device found» ... 
Bug... ??

BR
Marius

**Comment by MadMonkey87** [comment]
Hi, could you please open http://[IP ADRESS]:[PORT]/api/[API KEY]/sensors & http://[IP ADRESS]:[PORT]/api/[API KEY]/lights in your browser and post the results here? You'll need to replace the content in brackets with the according setting of the app config

**Comment by MadMonkey87** [comment]
I've added a little help in the latest version of the app. Please go into the app config, select 'support'. In that page please click on 'reload', then copy to clipboard and paste the content here. Thx

**Comment by MadMonkey87** [comment]
Is this still an issue or can I close the ticket?
