### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by powermarcel10** [MadMonkey87/HomeyCONZ#2]
Hi! 

Just a question.. I'm running homeyconz allready using this one: https://github.com/fantomnotabene/HomeyCONZ

Is this a clone of that app? Or something really new. Great to see it in the app store now! 

The thing I like to know; can I install this app as an update of the one I'm using now? Or do I need to re-add all my devices and re-configure all my flows...

**Comment by MadMonkey87** [comment]
Hey

Yes this is a fork of fantomnotabenes work but it is heavily modified and extended. Under the hood there us so much different that you can regard this as a totally new app. Unfortunately it is therefore not compatible the original one. But further updates are backwards compatible
