### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dirkg173** [MadMonkey87/HomeyCONZ#20]
**Describe the bug:**
IKEA KADRILJ blinds do not work in flows
With a simple flow (trigger = time / action = close, open or dim roller blind) the roller blinds neither close, nor open or move to a dim position. You can hear the motor for a short time, but nothing more happens.
Furthermore, the dimming level cannot be changed manually via the slider in the menu of the device card.
However, by pressing the device card or the button in the device card menu, the blinds can be fully opened or closed.
The blinds **cannot** be controlled via the Phoscon app either.

**How to reproduce:**
The misbehavior can be 100% reproduced according to the above description.

**How it should work:**
Open and close triggered by flows and move to a certain dimming level. Dimming level can be changed via slider.

**Screenshots:**
Just an example:
<img width="294" alt="Bildschirmfoto 2020-07-16 um 12 21 05" src="https://user-images.githubusercontent.com/40319629/87660152-e5887500-c75e-11ea-952c-f3a077c81d7d.png">

**Additional context:**

**Comment by MadMonkey87** [comment]
Hi,
Unfortunately I do not own this device so I need a little help from you. Can you please paste the api ressource info here? If you do not know how to do that you can go into the app configuration and then to the support tab

**Comment by dirkg173** [comment]
I hope this is correct:


{"config":{"UTC":"2020-07-20T18:59:18","apiversion":"1.16.0","backup":{"errorcode":0,"status":"idle"},"bridgeid":"00212EFFFF05B0C9","datastoreversion":"93","devicename":"ConBee II","dhcp":true,"factorynew":false,"fwversion":"0x26580700","gateway":"192.168.178.1","internetservices":{"remoteaccess":"disconnected"},"ipaddress":"192.168.178.57","linkbutton":false,"localtime":"2020-07-20T18:59:18","mac":"b8:27:eb:f8:b0:9d","modelid":"deCONZ","name":"ConBeeII","netmask":"255.255.255.0","networkopenduration":60,"panid":5250,"portalconnection":"disconnected","portalservices":false,"portalstate":{"communication":"disconnected","incoming":false,"outgoing":false,"signedon":false},"proxyaddress":"none","proxyport":0,"replacesbridgeid":null,"rfconnected":true,"starterkitid":"","swupdate":{"checkforupdate":false,"devicetypes":{"bridge":false,"lights":[],"sensors":[]},"notify":false,"text":"","updatestate":0,"url":""},"swupdate2":{"autoinstall":{"on":false,"updatetime":""},"bridge":{"lastinstall":"2020-06-15T18:09:08","state":"allreadytoinstall"},"checkforupdate":false,"install":false,"lastchange":"","lastinstall":"","state":"allreadytoinstall"},"swversion":"2.5.78","timeformat":"24h","timezone":"Etc/GMT","uuid":"3cedf0b6-ac81-4393-9d3d-b29d97c102a7","websocketnotifyall":true,"websocketport":443,"whitelist":{"0E2E8BF928":{"create date":"2020-07-13T06:26:22","last use date":"2020-07-16T17:45:08","name":"Hue Essentials#iPhone"},"40CF8C253E":{"create date":"2020-07-14T13:55:41","last use date":"2020-07-14T15:07:41","name":"Phoscon#B834x1042"},"6E5FF970E5":{"create date":"2020-07-14T21:05:11","last use date":"2020-07-15T10:32:02","name":"Phoscon#B834x1042"},"78CBFA1A78":{"create date":"2020-07-12T11:54:03","last use date":"2020-07-12T12:51:36","name":"Hue Essentials#iPad"},"A5C9AC357A":{"create date":"2020-07-14T10:06:46","last use date":"2020-07-14T13:40:36","name":"Phoscon#B1112x764"},"CE401F8843":{"create date":"2020-07-12T10:58:15","last use date":"2020-07-14T05:52:27","name":"Phoscon#B834x1042"},"D998E23C2A":{"create date":"2020-07-12T10:42:39","last use date":"2020-07-20T18:59:18","name":"homey"}},"zigbeechannel":25},"groups":{"1":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"b5c736b2ec482b6d8a09b0313bf0d029","id":"1","lights":["2","7"],"name":"Küche","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},"2":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":["2"],"etag":"f1fc06ab9825980ec03a4342fd5cd690","id":"2","lights":[],"name":"RWL021 2","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup","uniqueid":"00:17:88:01:08:0d:02:29"},"3":{"action":{"bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"etag":"3af2365f0042ab8e3bc977f2b6d889b3","id":"3","lights":["3","8","9"],"name":"Wohnzimmer","scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"}},"lights":{"1":{"etag":"e4d6cf41a0bc809518634eb6e20cb93a","hascolor":false,"lastannounced":null,"lastseen":"2020-07-20T18:59:12Z","manufacturername":"dresden elektronik","modelid":"ConBee II","name":"Configuration tool 1","state":{"reachable":true},"swversion":"0x26580700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:05:b0:c9-01"},"2":{"ctmax":500,"ctmin":153,"etag":"a4bd7faebcf4c0e44a600d0853a8af49","hascolor":true,"lastannounced":null,"lastseen":"2020-07-20T18:59:15Z","manufacturername":"Philips","modelid":"LST002","name":"Hue LightStrip","state":{"alert":"none","bri":176,"colormode":"hs","ct":153,"effect":"none","hue":47104,"on":false,"reachable":true,"sat":196,"xy":[0.2051,0.1227]},"swversion":"1.50.2_r30933","type":"Extended color light","uniqueid":"00:17:88:01:04:9a:b1:99-0b"},"3":{"etag":"d2d3f11c9ff9bfdb63a8e7de1bc220e3","hascolor":false,"lastannounced":"2020-07-20T09:31:07Z","lastseen":"2020-07-20T18:58:41Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI Signal Repeater","name":"TRADFRI Repeater Aquarium","state":{"alert":"none","reachable":true},"swversion":"2.2.005","type":"Range extender","uniqueid":"00:0d:6f:ff:fe:78:ee:df-01"},"7":{"etag":"ffc501ca29aa5d416597159a98f5897e","hascolor":false,"lastannounced":"2020-07-15T10:14:49Z","lastseen":"2020-07-20T18:58:56Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI Signal Repeater","name":"TRADFRI Repeater","state":{"alert":"none","reachable":true},"swversion":"2.2.005","type":"Range extender","uniqueid":"00:0d:6f:ff:fe:8e:85:60-01"},"8":{"etag":"d96eff51d30bd5a54bfb07ddfc5ab2ff","hascolor":false,"lastannounced":null,"lastseen":"2020-07-20T18:59:17Z","manufacturername":"IKEA of Sweden","modelid":"KADRILJ roller blind","name":"KADRILJ Rollo rechts","state":{"bri":0,"lift":0,"on":false,"open":false,"reachable":true},"swversion":"2.2.009","type":"Window covering device","uniqueid":"00:0d:6f:ff:fe:a2:07:21-01"},"9":{"etag":"d96eff51d30bd5a54bfb07ddfc5ab2ff","hascolor":false,"lastannounced":null,"lastseen":"2020-07-20T18:59:17Z","manufacturername":"IKEA of Sweden","modelid":"KADRILJ roller blind","name":"KADRILJ Rollo links","state":{"bri":0,"lift":0,"on":false,"open":false,"reachable":true},"swversion":"2.2.009","type":"Window covering device","uniqueid":"00:0d:6f:ff:fe:bb:34:4e-01"}},"resourcelinks":{"1":{"classid":3001,"description":"Resourcelink for switch rule","links":["/groups/1","/sensors/00:17:88:01:08:0d:02:29-02-fc00","/rules/1"],"name":"opt_on","owner":"CE401F8843","recycle":false,"type":"Link"},"2":{"classid":3002,"description":"Resourcelink for switch rule","links":["/groups/1","/sensors/00:17:88:01:08:0d:02:29-02-fc00","/rules/2"],"name":"opt_off","owner":"CE401F8843","recycle":false,"type":"Link"},"3":{"classid":3010,"description":"Resourcelink for switch rule","links":["/groups/1","/sensors/00:17:88:01:08:0d:02:29-02-fc00","/rules/3","/rules/4","/rules/5"],"name":"opt_pushDimUp","owner":"CE401F8843","recycle":false,"type":"Link"},"4":{"classid":3011,"description":"Resourcelink for switch rule","links":["/groups/1","/sensors/00:17:88:01:08:0d:02:29-02-fc00","/rules/6","/rules/7","/rules/8"],"name":"opt_pushDimDown","owner":"CE401F8843","recycle":false,"type":"Link"}},"rules":{"1":{"actions":[{"address":"/groups/1/action","body":{"on":true},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"1002"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T10:59:54","etag":"92a9b7dcc5b0ed7da5c0cf986d08577b","lasttriggered":"2020-07-16T19:34:05","name":"Rule ON","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":5},"2":{"actions":[{"address":"/groups/1/action","body":{"on":false},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"4002"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:06","etag":"b5c736b2ec482b6d8a09b0313bf0d029","lasttriggered":"2020-07-16T21:09:03","name":"Rule OFF","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":2},"3":{"actions":[{"address":"/groups/1/action","body":{"on":true},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"2002"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:18","etag":"9a93238cdf6ad707c5395f8819ec77e6","lasttriggered":"2020-07-16T19:34:02","name":"Rule PUSHDIMUP_ON","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":7},"4":{"actions":[{"address":"/groups/1/action","body":{"bri_inc":0},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"2003"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:18","etag":"58200536baf711b80edcd7be7498faf0","lasttriggered":"none","name":"Rule PUSHDIMUP_STOP","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":0},"5":{"actions":[{"address":"/groups/1/action","body":{"bri_inc":254,"transitiontime":30},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"2001"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:18","etag":"58200536baf711b80edcd7be7498faf0","lasttriggered":"none","name":"Rule PUSHDIMUP_START","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":0},"6":{"actions":[{"address":"/groups/1/action","body":{"on":false},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"3002"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:26","etag":"b6d33c5ed5cad92285d8c2136bb4a92e","lasttriggered":"2020-07-16T19:33:59","name":"Rule PUSHDIMDOWN_OFF","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":1},"7":{"actions":[{"address":"/groups/1/action","body":{"bri_inc":-254,"transitiontime":30},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"3001"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:26","etag":"58200536baf711b80edcd7be7498faf0","lasttriggered":"none","name":"Rule PUSHDIMDOWN_START","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":0},"8":{"actions":[{"address":"/groups/1/action","body":{"bri_inc":0},"method":"PUT"}],"conditions":[{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/buttonevent","operator":"eq","value":"3003"},{"address":"/sensors/00:17:88:01:08:0d:02:29-02-fc00/state/lastupdated","operator":"dx"}],"created":"2020-07-12T11:00:26","etag":"58200536baf711b80edcd7be7498faf0","lasttriggered":"none","name":"Rule PUSHDIMDOWN_STOP","owner":"CE401F8843","periodic":0,"status":"enabled","timestriggered":0}},"scenes":{},"schedules":{},"sensors":{"1":{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"etag":"58200536baf711b80edcd7be7498faf0","manufacturername":"Philips","modelid":"PHDL00","name":"Daylight","state":{"dark":false,"daylight":true,"lastupdated":"2020-07-20T18:50:07.800","status":180,"sunrise":"2020-07-20T03:43:55","sunset":"2020-07-20T19:40:51"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:b0:c9-01"},"2":{"config":{"battery":100,"group":"2","on":true,"reachable":true},"ep":2,"etag":"dd46ecd0d0d89001435ba4b411464dc0","lastseen":"2020-07-20T18:57:51.507","manufacturername":"Philips","mode":1,"modelid":"RWL021","name":"Dimmschalter LightStrip","state":{"buttonevent":4002,"eventduration":1,"lastupdated":"2020-07-16T21:09:03.049"},"swversion":"6.1.1.28573","type":"ZHASwitch","uniqueid":"00:17:88:01:08:0d:02:29-02-fc00"},"3":{"config":{"on":true,"reachable":true},"ep":1,"etag":"28295a926bb48f289eb6b7affa61a4e1","lastseen":"2020-07-20T18:59:17.551","manufacturername":"IKEA of Sweden","modelid":"KADRILJ roller blind","name":"KADRILJ roller blind ","state":{"battery":48,"lastupdated":"2020-07-20T18:22:26.042"},"swversion":"2.2.009","type":"ZHABattery","uniqueid":"00:0d:6f:ff:fe:a2:07:21-01-0001"},"4":{"config":{"on":true,"reachable":true},"ep":1,"etag":"054ef519b4edcefff35bae2692b97c8a","lastseen":"2020-07-20T18:59:17.584","manufacturername":"IKEA of Sweden","modelid":"KADRILJ roller blind","name":"KADRILJ roller blind ","state":{"battery":65,"lastupdated":"2020-07-20T18:33:48.161"},"swversion":"2.2.009","type":"ZHABattery","uniqueid":"00:0d:6f:ff:fe:bb:34:4e-01-0001"}},"wsConnected":true}

**Comment by MadMonkey87** [comment]
Thx that's exactly what's needed. As this one is a little bit more complex to handle properly it will take some time but I think I'll be able to support this one properly

**Comment by MadMonkey87** [comment]
Short update: I haven't forgotten about this one, I just had no time yet. Hopefully I'll be able to provide an update soon...

**Comment by MadMonkey87** [comment]
Provided with 1.24
