### ISSUE TITLE
Dicovery not working at all

### ISSUE THREAD

**Issue by rafi1975** [MadMonkey87/HomeyCONZ#21]
I just installed the CONZ app on my Homey and tried the discovery. It comes back with - error:Unable to find a deCONZ gateway. deCONZ app is at v1.11.3 and Homey at 4.2.0. I was able to configure the connection manually with IP address, port and API key which is now available on deCONZ app. Connectivity test runs ok with only one warning re WEBSOCKETS. However the app keeps crashing once I did that.  Between crashes I tried adding Philips HUE motion sensor that works ok on deCONZ gateway and Homey app can't find it at all.

**Comment by MadMonkey87** [comment]
Hi, I guess there are actually two errors here.
1) discovery: not really a problem, but looks like you've disabled it. Are you using a docker container and are you missing --net host param?
2) You have most likely not configured the ws port correctly. In the app configuration there is a support page, do you get any content there and could you please post it here?

**Comment by rafi1975** [comment]
Hi,

re. 1. What do you mean by 'you've disabled it'? I'm using Raspberry Pi 2 with the image provided by deCONZ, from their website, the stable one.
re. 2. I haven't configured WS at all. I'm not sure where it should be done - at Raspbian level? In the app on Homey on Suport tab I can see two buttons - Reload and Copy to clipboard. None really does anything.

Thanks

**Comment by MadMonkey87** [comment]
1) What happens if you open http://phoscon.de/discover? If it returns [] you have done something wrongly with your deconz setup
2) you need to configure the ws port in the app config (websocket port). Note that you need to enter all 4 fields there and then click on save. If everything is correct you should then also get some details in the support tab

**Comment by rafi1975** [comment]
Re.1 Yup. When I open that discovery website it comes back with only [].
Re.2 I think the issue is with that image for Raspbian provided by deCONZ. I haven’t touched anything there. So I presume the only option is to install deCONZ on Raspian from scratch not using their image.

**Comment by MadMonkey87** [comment]
That would be one option, but you mentioned that you were actually able to open the phoscon app itself? That would mean that you still have a running instance and that you could connect to that.

**Comment by rafi1975** [comment]
Yes,I can connect to it on Raspberry Pi with no issues. Problems start when I try it from Homey app. I guess at this stage the only option is to install it manually. I’l give it a go.

Thanks

**Comment by rafi1975** [comment]
Defo something wrong with either Raspberry or the deCONZ image. When installed on Windows 10 all is flying.

**Comment by rafi1975** [comment]
As per my last update, I came to a conclusion that therr must be something wrong with your app. Using the same hardware ConBee2 on Windows 10 all is absolutely ok.When using Raspberry Pi your app can’t handle it. On the other hand all is functioning ok when using raspberry pi app. I’m not trying to blame anyone but this is where we are. Do you have any other Raspberry Pi users that have no issues? It’s a pity as I have 4 spare Raspberry Pi’s and they are useless at this stage.

Regards,

Raf

**Comment by MadMonkey87** [comment]
I would not say that my app is bug free but it is really only you who have this issue and we haven't proved yet that your setup actually works. Can you post what values you have entered for ip, port, apikey and websocket port? What response do you get if you open http://[your ip]:[your port]/api/[your api key]?

**Comment by rafi1975** [comment]
Hi,

At the beginning please accept my apologies. It wasn’t your app. Today deCONZ prompted for firmware update on my ConBee 2 and once done it couldn’t connect back to and it was keeping to perform another firmware update - a loop. Then I did manual firmware update using their tool. The same issue. Eventually I did that once again and it worked. Your app was able to discover the gateway and I was able to add the devices to Homey. My joy was gone after a sudden power loss in my area. Once Raspberry came back online, deCONZ app couldn’t find the ConBee stick. I replugged it to another USB port and it was recognised again. I tested it several times and it’s always the same after the Raspberry reboots. It has to be inserted into different USB port. Weird.
