### ISSUE TITLE
Bitron Wandthermostat mit Relais 902010/32

### ISSUE THREAD

**Issue by madmax75** [MadMonkey87/HomeyCONZ#29]
**Device name:**
Bitron Wandthermostat mit Relais 902010/32

**Device link:**
https://manuals.smabit.eu/lde/av2010_32.html 

**Device modelid:**
902010/32

**Device capabilities:**
Heizen/Kühlen/Aus

**State report example:**

**Comment by MadMonkey87** [comment]
Hi, can you please show me how this device looks trough the api? If you do not know how to do this please do the following in the homey app:

- go to the app config->advanced
- scroll down to usage data and click on "copy"; then paste the content here

**Comment by MadMonkey87** [comment]
Please have a look at the latest beta [release](https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/) which provides generic support for your device. Feel free to reopen the ticket if needed

**Comment by madmax75** [comment]
Hi. I integrated the thermostat again via the Bitron Homey app.

7. Februar 2021 14:19, "Philippe Wechsler" <notifications@github.com (mailto:notifications@github.com?to=%22Philippe%20Wechsler%22%20<notifications@github.com>)> schrieb:
	Hi, can you please show me how this device looks trough the api? If you do not know how to do this please do the following in the homey app: 
	* go to the app config->advanced 
	* scroll down to usage data and click on "copy"; then paste the content here
