### ISSUE TITLE
Friends of Hue (Feller Edizio Due)

### ISSUE THREAD

**Issue by gajdur** [MadMonkey87/HomeyCONZ#3]
Hi, any chance to implement the Feller Switch?
I already posted all Events here:
https://github.com/fantomnotabene/HomeyCONZ/issues/41

Thanks

**Comment by MadMonkey87** [comment]
Hi, looks like that would be possible, yes! I'll have a deeper look on it for the next update. 

Btw: you should be able to use the switch already using the <Generic Wireless Switch>, does that work?

**Comment by gajdur** [comment]
Hi, sorry not installed yet your App, going to migrate in the next days. Or can i use parallel both Apps, your and the notabene?

**Comment by MadMonkey87** [comment]
you can use both in parallel, but you cannot migrate from one to another

**Comment by MadMonkey87** [comment]
Can you confirm the following?
The Button Layout is something like that:
1  |  2
------
3  |  4

modelid = FOHSWITCH

button 1 & 3 = button 5
button 2 & 4 = button 6

all buttons (include 5 & 6) support the following events:
 - inital press (event x000)
- release (event x0002)
- hold (event x0001)
- release after hold (event x003)

double press is not supported?

**Comment by MadMonkey87** [comment]
I've integrated the device, can you please test it at https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/ ?

**Comment by gajdur** [comment]
Wow, works perfect, single press, hold, dual buttons 5 and 6. And no, double click has no event. Thank you very much.
