### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZeppDK** [MadMonkey87/HomeyCONZ#31]
**Describe the bug:**
After the latest Update deconz app keeps chrashing as soon as its startet

**How to reproduce:**
Start deconz app

**How it should work:**
Like in the old version of the app

**Screenshots:**
Not much to see, as it just dies

**Additional context:**
Homey debug id 1ff4a6d1-dccd-4c2c-81c3-599de19e962b

**Comment by ZeppDK** [comment]
![Uploading 45EDE4E7-69F4-4188-9D73-09E26C09BE7E.png…]()

**Comment by MadMonkey87** [comment]
Hi,

This should be fixed in the latest version, can you confirm?
