### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gajdur** [MadMonkey87/HomeyCONZ#32]
**Describe the bug:**
App v1.16.0 is crashing immediately after restart

**How to reproduce:**
Restart the App and wait couple seconds

**How it should work:**
like yesterday :-)
5475413d-8c69-4595-9628-5200ce4ee292

**Comment by MadMonkey87** [comment]
Hi,

This should be fixed in the latest version, can you confirm?

**Comment by gajdur** [comment]
Hi,

yes, not crashing anymore.

Thanks
