### ISSUE TITLE
Lights not going out in the app and sockets behave strange

### ISSUE THREAD

**Issue by powermarcel10** [MadMonkey87/HomeyCONZ#35]
The following happend since I'm using version 17.0/17.1

When I turn of a light in the app, it goes back on (in the app) and it keeps thinking that the light is still on. But it isn’t.

So when a next flow is executed to turn the light on, nothing happened, because the app still thinks that the light is allready on.

Also, the sockets from innr in my case go randomly on/off in the app. In real time, nothing happend and there is no flow that triggers this. So something strange is going on..

**Comment by MadMonkey87** [comment]
Hi, this should be resolved with >= 1.17.2

Can you confirm this?
