### ISSUE TITLE
IKEA TRÅDFRI Wireless Open/Close Remote E1766

### ISSUE THREAD

**Issue by dirkg173** [MadMonkey87/HomeyCONZ#37]
**Device name:**
IKEA TRÅDFRI Wireless Open/Close Remote E1766

**Device link:**
https://www.ikea.com/de/de/manuals/kadrilj-roller-blind-wireless-battery-operated-grey__AA-2172195-2_pub.pdf

**Device modelid:**
TRADFRI open/close remote

**Device capabilities:**
up/down (Events 23, 23; acc. to [deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices))

**State report example:**
I do not know how to provide these informations.
But the remote is already correctly identified by the Phoscon app, so I hope that these data are already publicly available.

**Comment by MadMonkey87** [comment]
Hey, this device should already be supported: 
![20210123_150028](https://user-images.githubusercontent.com/29612400/105580300-da587680-5d8b-11eb-8ace-1072b16b1161.png)

**Comment by dirkg173** [comment]
Trådfri Square Dimmer ([E1743](https://www.ikea.com/de/de/manuals/tradfri-wireless-dimmer__AA-2171511-1_pub.pdf)) and Trådfri Wireless Open/Close Remote ([E1766](https://www.ikea.com/de/de/manuals/kadrilj-roller-blind__AA-2172195-2_pub.pdf)) are two different devices, aren't they?

**Comment by MadMonkey87** [comment]
I am not really sure, seems that they really behave the same way, maybe the just have a different model id. On the site you mentioned I only see one device? Currently this driver supports the following model id's:
- TRADFRI on/off switch
- TRADFRI open/close remote

Are you able to get the model id of your device?

**Comment by dirkg173** [comment]
In my last comment there are two links, one for the Dimmer E1743 and one for the O/C Remote E1766.

Function and ID Dimmer E1743: 
![BF95758A-6D91-4ED1-9412-2A890D220FF9](https://user-images.githubusercontent.com/40319629/105622439-13d3c500-5e12-11eb-8ea0-5dd35800050e.jpeg)
![9E49AE43-C365-429A-8A71-604AA8C507F1](https://user-images.githubusercontent.com/40319629/105622662-8e511480-5e13-11eb-8a73-400c7f27fde1.jpeg)


Function O/C Remote E1766:
![A8D4B6BA-B4D7-4094-9D4F-2258CD31B900](https://user-images.githubusercontent.com/40319629/105622487-6ca35d80-5e12-11eb-9d30-1fe826a0b5b9.jpeg)
![81C5774D-F889-419A-9308-EB7498471223](https://user-images.githubusercontent.com/40319629/105622639-62ce2a00-5e13-11eb-8553-566d9bd89747.jpeg)

Actually I have connected both switches directly with Homey again.

**Comment by MadMonkey87** [comment]
Ikea might sell this as two different devices, but it seems the only difference is that they have a different model id (they both support the same button events). As this are the ones already supported by the app I am pretty sure it will work out of the box if you use just the "Tradfri Square Dimmer" driver. Or did you already try this?

**Comment by dirkg173** [comment]
Because it is not logical for me to use a light dimmer to operate blinds, so I didn't try it.
I included them as a "Generic Button". Beside the fact that it is not intuitive to create the logic events (1002, 2002,...), the "Generic Button" does not look really good.
In the meantime I connected them directly with Homey again.
