### ISSUE TITLE
Feature Request: Lampen Aktionskarten mit Übergangszeit erweitern

### ISSUE THREAD

**Issue by dirkg173** [MadMonkey87/HomeyCONZ#38]
Bei meinen Hue sowie Innr Lampen ist es möglich Aktionskarten mit einer optionalen und frei definierbaren Übergangszeit ausführen zu lassen.
Bei folgenden Aktionskarten ist das möglich:
- Dimmen auf
- Relatives Dimmniveau setzen
- Den Farbton setzen
- Eine Farbe setzen
- Eine zufällige Farbe setzen
- Die Sättigung setzen
- Eine Temperatur setzen

Beispiel:
![A98F82D9-396A-4C50-B249-3F67533FCCB2](https://user-images.githubusercontent.com/40319629/103498831-5a9f5200-4e46-11eb-93ab-c8df474d6302.jpeg)

Welche dieser Aktionskarten verfügbar sind, ist natürlich von der Lampenausführung (16 Mio. Farbe / White Ambiance / nur dimmbar) abhängig.
Diese Aktionskarten stehen sowohl in der Philips Hue App (mit Bridge), als auch in der Philips Hue Zigbee und Innr Lighting Devices App zur Verfügung. Diese Möglichkeit ist also kein Alleinstellungsmerkmal von Philips Hue in Verbindung mit einer Hue Bridge.

Ist es möglich Aktionskarten in der deCONZ App entsprechend zu erweitern?

**Comment by MadMonkey87** [comment]
Hi, please try to stick to english s.t other users can understand our conversation too;) The next release will contain an action card for lights and groups that allow you set all properties individually, including the transition time

**Comment by dirkg173** [comment]
Sorry for asking in German.
The new features sounds good!
