### ISSUE TITLE
Opple Switch not working

### ISSUE THREAD

**Issue by HeJoVe1547** [MadMonkey87/HomeyCONZ#41]
**Describe the bug:**

Opple 3-Switch doesn't work with Conbee II
Switch is registered but it's state is not communicated to Homey.

**How to reproduce:**

**How it should work:**

**Screenshots:**

**Additional context:**

**Comment by MadMonkey87** [comment]
Hey @HeJoVe1547 
Were you able to add the switch in homey and no flows where triggered when you press the switch or were you not even able to add it in homey?

**Comment by HeJoVe1547** [comment]
Exactly that is my problem.
Am 23. Jan. 2021, 14:57 +0100 schrieb Philippe Wechsler <notifications@github.com>:

**Comment by MadMonkey87** [comment]
Which of the two?!?

**Comment by HeJoVe1547** [comment]
I was able to add the switch in homey. Impossible to trigger on it. An Aqara leak sensor is working fine. So I guess my installation is ok.
Am 23. Jan. 2021, 20:07 +0100 schrieb Hein Versteeg <hversteeg@t-online.de>:

**Comment by Birger90** [comment]
I have the same Problem.  And I can't trigger any actions in phoscon app

**Comment by MadMonkey87** [comment]
To verify if this is an problem in the app or within deconz (seems the device has some issues there) please do the following:

- Open up a websocket connection to ws://[ip address from the config]:[web socket port]. If you do not now how to do this you might use this app for example: https://play.google.com/store/apps/details?id=com.technologies.hps.websockettools
- Depending on your deconz you might now get a lot of messages. Please try to press buttons on your ople device and check if you get some events from that
- if you do not get them this is not a problem of the app but of deconz -> please open an issue in the official deconz repo
- if you do, please post them here and also a screenshot of the device settings in the homey app (the info part)

**Comment by MadMonkey87** [comment]
Most likely this is related to https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4272 which is fixed by the latest DeConz release. Please try again after updating and reopen the ticket if this does not resolve this case
