### ISSUE TITLE
No active Alert status displayed on device icon for newly added motion sensors

### ISSUE THREAD

**Issue by iisworks** [MadMonkey87/HomeyCONZ#47]
**Describe the bug:**

When you add a new Aqara motion sensor, no orange alert indicator is displayed on the device icon when it triggers. The same issue occurs with Aqara Vibration sensors and motion sensors of other brands as well. 

**How to reproduce:**

- Add an Aqara motion sensor
- Trigger motion
- No alert indicator is displayed on the device icon

**How it should work:**

**Screenshots:**
Missing:
![image](https://user-images.githubusercontent.com/33196233/112527472-60e8fe80-8da3-11eb-9073-a8cc2ff50451.png)

**Additional context:**

This still works for existing devices that were added previously. Note: the alert is still shown on the device info page + history, and flows are still triggered.-

**Comment by MadMonkey87** [comment]
Very strange, I am not sure what's happening here yet. This might as well be an homey issue too as there is no way to explicit set this icon and homey does this implicit. What happens if you
- restart the app
- restart homey
?

**Comment by iisworks** [comment]
I alreay tried that, but I think this has been an issue since version 1.22 or maybe 1.21. It did work before, and when I pair a sensor directly to Homey 5.0.4 it also works fine. This issue was also confirmed by others, and even with other motion sensors brands?

**Comment by ictforall** [comment]
Also have this problem, not only with motion sensors, but with all newly added sensors.
- Aqara motion sensor
- Aqara door sensor
- Aqara water sensor

Only on a group it shows an alarm indicator on the tile icon.

Restart app, restart homey, restart deCONZ did not work.

**Comment by mauriceot** [comment]
I also noticed this in Homey, that all sensors do not show when they are active.
But when using Homeydash, it does work correct! All sensors show their active status there.

**Comment by MadMonkey87** [comment]
I think this is an homey issue and I've created a ticket for Athom over here: https://github.com/athombv/homey-apps-sdk-issues/issues/189

Even reverting to very old versions seem not to resolve the problem so this is a strong indicator this is not a problem of the app.

Did somebody try it in the web app? If it works there it might just be an ios/android app problem

**Comment by mauriceot** [comment]
Just tried it in the webapp and it does not work there either.
Homeydash seems the only thing it works in.

**Comment by ictforall** [comment]
> Just tried it in the webapp and it does not work there either.
> Homeydash seems the only thing it works in.

Yes can confirm that, does not work in webapp.

**Comment by iisworks** [comment]
Indeed the WebApp does know an alert triggered (red dot), but does not show the orange indicator on newly added devices (should be on the right side of the grey line):
![image](https://user-images.githubusercontent.com/33196233/113710217-b8606600-96e3-11eb-9313-7ce2b2a58bca.png)

OK, let's wait what Athom says!

**Comment by MadMonkey87** [comment]
It indeed is an homey issue that will be fixed by Athom, see https://github.com/athombv/homey-apps-sdk-issues/issues/189
