### ISSUE TITLE
[DEVICE REQUEST] Hue wall switch

### ISSUE THREAD

**Issue by wunni1** [MadMonkey87/HomeyCONZ#49]
**Device Name & Manufacturer**
Hue wall switch

**Device Description Link**

https://www.philips-hue.com/de-de/p/hue-philips-hue-wall-switch-modul/8719514318045

**Device state as reported by deConz**

{"wsConnected":true,"usageId":"ec254fea-cc17-4d83-be89-8251db398f30","deCONZ":{"apiversion":"1.16.0","datastoreversion":"93","dhcp":true,"fwversion":"0x26680700","swversion":"2.11.0","websocketnotifyall":true,"name":"Conbee2","mac":"dc:a6:32:3c:b8:05","zigbeechannel":15,"panid":43765,"devicename":"ConBee II"},"groups":[{"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"id":"1","lights":["2","3","4","5","6"],"scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},{"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"id":"2","lights":["7","8","9","10","11","12"],"scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},{"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"id":"3","lights":["14","15"],"scenes":[],"state":{"all_on":false,"any_on":false},"type":"LightGroup"},{"action":{"alert":"none","bri":127,"colormode":"hs","ct":0,"effect":"none","hue":0,"on":false,"sat":127,"scene":null,"xy":[0,0]},"devicemembership":[],"id":"4","lights":["13","16"],"scenes":[],"state":{"all_on":false,"any_on":true},"type":"LightGroup"}],"lights":[{"hascolor":false,"lastannounced":null,"lastseen":"2021-04-14T22:05Z","manufacturername":"dresden elektronik","modelid":"ConBee II","state":{"reachable":true},"swversion":"0x26660700","type":"Configuration tool","uniqueid":"00:21:2e:ff:ff:05:aa:02-01"},{"hascolor":false,"lastannounced":"2021-03-19T18:58:40Z","lastseen":"2021-04-14T22:05Z","manufacturername":"OSRAM","modelid":"Plug 01","state":{"alert":"none","on":false,"reachable":true},"swversion":"V1.04.90","type":"On/Off plug-in unit","uniqueid":"7c:b0:3e:aa:00:af:ba:6f-03"},{"colorcapabilities":31,"ctmax":666,"ctmin":125,"hascolor":true,"lastannounced":"2021-03-19T18:58:38Z","lastseen":"2021-04-14T22:05Z","manufacturername":"OSRAM","modelid":"Gardenpole RGBW-Lightify","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"effect":"none","hue":0,"on":false,"reachable":true,"sat":0,"xy":[0.3805,0.3769]},"swversion":"V1.04.93","type":"Extended color light","uniqueid":"7c:b0:3e:aa:00:a9:56:87-03"},{"colorcapabilities":31,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-03-19T18:58:41Z","lastseen":"2021-04-14T22:06Z","manufacturername":"OSRAM","modelid":"Gardenpole Mini RGBW OSRAM","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"effect":"none","hue":0,"on":false,"reachable":true,"sat":0,"xy":[0.3805,0.3769]},"swversion":"V1.05.10","type":"Extended color light","uniqueid":"7c:b0:3e:aa:00:ab:1f:c4-03"},{"colorcapabilities":31,"ctmax":666,"ctmin":125,"hascolor":true,"lastannounced":"2021-03-19T18:58:41Z","lastseen":"2021-04-14T22:06Z","manufacturername":"OSRAM","modelid":"LIGHTIFY Outdoor Flex RGBW","state":{"alert":"none","bri":154,"colormode":"ct","ct":370,"effect":"none","hue":0,"on":false,"reachable":true,"sat":0,"xy":[0.3805,0.3769]},"swversion":"V1.04.93","type":"Extended color light","uniqueid":"7c:b0:3e:aa:00:a9:fb:46-03"},{"colorcapabilities":31,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-03-19T18:23:22Z","lastseen":"2021-04-14T18:59Z","manufacturername":"OSRAM","modelid":"Gardenpole Mini RGBW OSRAM","state":{"alert":"none","bri":1,"colormode":"ct","ct":370,"effect":"none","hue":0,"on":false,"reachable":false,"sat":0,"xy":[0.3805,0.3769]},"swversion":"V1.05.10","type":"Extended color light","uniqueid":"7c:b0:3e:aa:00:ab:1c:0b-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-11T20:11:11Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:00:7c:1a-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-11T20:11:11Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:00:93:65-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-11T20:11:12Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:00:83:b8-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-11T20:11:11Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:01:36:c0-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-14T14:31:24Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:00:7c:c5-03"},{"colorcapabilities":16,"ctmax":370,"ctmin":153,"hascolor":true,"lastannounced":"2021-04-11T20:11:11Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"PAR16 50 TW","state":{"alert":"none","bri":254,"colormode":"ct","ct":370,"on":false,"reachable":true},"swversion":"V1.03.07","type":"Color temperature light","uniqueid":"84:18:26:00:00:01:3a:61-03"},{"hascolor":false,"lastannounced":"2021-03-07T14:55:30Z","lastseen":"2021-04-14T22:07Z","manufacturername":"OSRAM","modelid":"Classic A60 W clear - LIGHTIFY","state":{"alert":"none","bri":1,"on":false,"reachable":true},"swversion":"V1.04.12","type":"Dimmable light","uniqueid":"7c:b0:3e:aa:00:ac:16:a8-03"},{"ctmax":65279,"ctmin":0,"hascolor":true,"lastannounced":null,"lastseen":"2021-04-14T22:06Z","manufacturername":"LIDL Livarno Lux","modelid":"HG06106B","state":{"alert":"none","bri":255,"colormode":"ct","ct":153,"on":false,"reachable":true,"xy":[0.1987,0.0569]},"swversion":null,"type":"Extended color light","uniqueid":"84:2e:14:ff:fe:22:0a:f4-01"},{"hascolor":false,"lastannounced":"2021-04-13T00:26:57Z","lastseen":"2021-04-14T22:05Z","manufacturername":"Nanoleaf","modelid":"NL08-0800","state":{"alert":"none","bri":166,"on":false,"reachable":true},"swversion":"1.3.1","type":"Dimmable light","uniqueid":"00:0d:6f:00:0b:59:21:d4-01"},{"hascolor":false,"lastannounced":null,"lastseen":"2021-04-14T22:07Z","manufacturername":"SONOFF","modelid":"01MINIZB","state":{"alert":"none","on":true,"reachable":true},"swversion":"20200927","type":"On/Off light","uniqueid":"80:4b:50:ff:fe:a6:b7:67-01"}],"sensors":[{"config":{"configured":true,"on":true,"sunriseoffset":30,"sunsetoffset":-30},"manufacturername":"Philips","modelid":"PHDL00","state":{"dark":true,"daylight":false,"lastupdated":"2021-04-14T20:07:26.771","status":230,"sunrise":"2021-04-14T04:32:29","sunset":"2021-04-14T18:10:03"},"swversion":"1.0","type":"Daylight","uniqueid":"00:21:2e:ff:ff:05:aa:02-01"},{"config":{"battery":100,"on":true,"reachable":true,"temperature":0},"ep":1,"lastseen":"2021-04-14T21:54Z","manufacturername":"LUMI","modelid":"lumi.sensor_magnet.aq2","state":{"lastupdated":"2021-04-14T21:54:32.860","open":false},"swversion":"20161128","type":"ZHAOpenClose","uniqueid":"00:15:8d:00:04:4a:ae:88-01-0006"},{"config":{"battery":100,"on":true,"reachable":true,"temperature":2900},"ep":1,"lastseen":"2021-04-14T21:21Z","manufacturername":"LUMI","mode":1,"modelid":"lumi.remote.b1acn01","state":{"buttonevent":1002,"lastupdated":"2021-04-14T15:30:22.622"},"swversion":"20180525","type":"ZHASwitch","uniqueid":"00:15:8d:00:02:83:d3:9b-01-0012"},{"config":{"battery":100,"offset":0,"on":true,"reachable":true},"ep":1,"lastseen":"2021-04-14T21:53Z","manufacturername":"LUMI","modelid":"lumi.weather","state":{"lastupdated":"2021-04-14T21:53:46.594","temperature":2016},"swversion":"20191205","type":"ZHATemperature","uniqueid":"00:15:8d:00:05:42:a9:c3-01-0402"},{"config":{"battery":100,"offset":0,"on":true,"reachable":true},"ep":1,"lastseen":"2021-04-14T21:53Z","manufacturername":"LUMI","modelid":"lumi.weather","state":{"humidity":5109,"lastupdated":"2021-04-14T21:53:46.614"},"swversion":"20191205","type":"ZHAHumidity","uniqueid":"00:15:8d:00:05:42:a9:c3-01-0405"},{"config":{"battery":100,"on":true,"reachable":true},"ep":1,"lastseen":"2021-04-14T21:53Z","manufacturername":"LUMI","modelid":"lumi.weather","state":{"lastupdated":"2021-04-14T21:36:12.485","pressure":965},"swversion":"20191205","type":"ZHAPressure","uniqueid":"00:15:8d:00:05:42:a9:c3-01-0403"},{"config":{"battery":100,"devicemode":"singlerocker","on":true,"pending":[],"reachable":true},"ep":1,"lastseen":"2021-04-14T22:03Z","manufacturername":"Signify Netherlands B.V.","mode":1,"modelid":"RDM001","state":{"buttonevent":1002,"eventduration":1,"lastupdated":"2021-04-14T17:02:08.636"},"swversion":"1.0.3","type":"ZHASwitch","uniqueid":"00:17:88:01:0b:00:1a:1b-01-fc00"},{"config":{"battery":100,"devicemode":"singlerocker","on":true,"pending":[],"reachable":true},"ep":1,"lastseen":"2021-04-14T17:03Z","manufacturername":"Signify Netherlands B.V.","mode":1,"modelid":"RDM001","state":{"buttonevent":1002,"eventduration":1,"lastupdated":"2021-04-14T17:03:51.127"},"swversion":"1.0.3","type":"ZHASwitch","uniqueid":"00:17:88:01:0b:00:1a:1f-01-fc00"}]}

**Additional context**
More information see:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4566

**Comment by MadMonkey87** [comment]
I've created a new beta release that supports the hue switch. I've also seen that you're using an sonoff device that does not yet have support and added it as well.

The icon is not yet right but you can grab the latest beta from here: https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

Please let me know if everything works and buy me a beer if you're happy with the app;)
