### ISSUE TITLE
app wont get api key from deconz

### ISSUE THREAD

**Issue by ZeppDK** [MadMonkey87/HomeyCONZ#5]
**Describe the bug:**
the homey app wont get an api key from deconz,
i have activated the "authenticate app" button in deconz/phoscon
then pressed the auto discovery in the homey app,
it says "successfully autodiscovered gateway"

but if i try to add a device, it asks me to go to the app settings and fill in all fields,

if i then go to app settings and click advanced, it has found the right IP, and the web port, but dont have the websocket port filled in, or an api key.
i have tried re-installing the app

**How to reproduce:**
by trying to authenticate again

**How it should work:**
press authenticate, get positive respons, the all settings auto filled, add devices..

**Comment by satoer** [comment]
I have the same problem. But I'm using the Phoscon App. At least I think. I've thought I installed deconz in a docker container on my Synology. But when I go to the web interface I see the Phoscon app. Everything seems to work in there (I can find Aqara sensors). But I've the same problem as ZeppDK inside Homey.

**Comment by ZeppDK** [comment]
im using the "Homebridge-hue + Raspbian Buster" deconz image from phoscon.de

deCONZ version 2.05.72

**Comment by ZeppDK** [comment]
now i have also tried reinstalling deconz in a docker container instead of my raspberry pi, same result.. the homey app finds deconz, but dosnt get an api key...

**Comment by ZeppDK** [comment]
I have made a diagnostics report if that helps 901eae69-16b7-4ffa-9939-97b7f9a1bc4e

**Comment by ZeppDK** [comment]
i think i found the bug!!!
it didnt work from the iphone app....
but then i tried doing it from http://developer.athom.com/tools/app-settings instead, and it worked!

so it seems that there is something the iphone app dont like

**Comment by satoer** [comment]
Didn't solve the problem in my case. It also show the wrong IP adress. And it even authenticates when I don't activate the authentication option inside Phoscon. It even authenticates when I completely disable the docker app. But with the wrong credentials: Wrong ip adress and no api key etc.

**Comment by ZeppDK** [comment]
> Didn't solve the problem in my case. It also show the wrong IP adress. And it even authenticates when I don't activate the authentication option inside Phoscon. It even authenticates when I completely disable the docker app. But with the wrong credentials: Wrong ip adress and no api key etc.

do your docker container have its own ip in the same ip range as homey?
i had the same problem until i found out that my deconz was on the wrong network, THEN i got the errors with it detecting the gw ip correct but not getting a api key :)

**Comment by satoer** [comment]
Re-installed the docker deconz image. Now it seems to work! This time I checked "Use same network as docker host" before installing. After installation I still got the wrong IP Adress using the auto discovering feature of the Homey-app. It's probably getting the information from this link:
https://phoscon.de/discover
Reinstalled Homey App, still wrong IP (and no API key)
Restarted docker image, and it seems to work! When using auto discover it now wants you to enable the "Authentication" option in Phoscon. (It previously stated that is authenticated (without the option enabled). Authenticated it, and the app filled in every field, including the API key. Also a test zigbee device seems to work!

So, if you have problems check if the right ip address and port is properly communicated to:
https://phoscon.de/discover

If not, adjust network settings inside docker.

**Comment by MadMonkey87** [comment]
There is also a discussion about this in the official community thread of this app. Here are some points to note:

- ensure that your smartphone is in the same network as deconz when setting up the homey app
- if you're using the docker image of marthoc you must use the parameter --net=host in order to have the autodiscovery working. This is something that cannot be solved in the app or in the docker image otherewise!
 - if you do not wan't to use --net=host this is perfectly fine, but the autodiscovery won't work correct in that case. In the app config you then simply need to click on "advanced" and enter all details manually and click on save. Important: to prevent a wrongly discovered ip it is recommended to use the DECONZ_UPNP=0 parameter to disable discovery.

The only thing I can improve on the app is to detect when an wrong ip has been detected but I cannot make a working discovery if you're not using the --net=host parameter (which is also mentioned like that by marthoc) and basically is the idea behind not using this parameter

**Comment by ZeppDK** [comment]
> “ensure that your smartphone is in the same network as deconz when setting up the homey app“

might have been my problem, as both homey and deconz is on my IOT network, and my phone is on my normal network.
But the funny thing was still that the Discovery found both the right ip, and webport.. so it semi worked and didnt come with a usefull error.. so didnt Think that the iPhones network was important for linking 2 devices on the same network :-)

**Comment by MadMonkey87** [comment]
Please check out the latest release as it contains some improved setup mechanisms. Please feel free to reopen the ticket or create a new one if there are still issues
