### ISSUE TITLE
[DEVICE REQUEST]

### ISSUE THREAD

**Issue by powermarcel10** [MadMonkey87/HomeyCONZ#51]
heiman hs1rc-ef

https://nl.aliexpress.com/item/32892074229.html

**Device state as reported by deConz**

"manufacturername":"Heiman","mode":1,"modelid":"RC-EF-3.0","state":{"buttonevent":4002,"lastupdated":"2021-04-19T22:09:25.875"},"swversion":"2019.9.10","type":"ZHASwitch","uniqueid":"ec:1b:bd:ff:fe:0f:a7:7d-01-0501"}]}

(There is also 1002, 2002 and 3002 as button event.)

 },
    "142": {
      "config": {
        "battery": null,
        "on": true,
        "reachable": true
      },
      "ep": 1,
      "etag": "d06f52efbd9112d424822113bbace636",
      "lastseen": "2021-04-19T22:09Z",
      "manufacturername": "Heiman",
      "mode": 1,
      "modelid": "RC-EF-3.0",
      "name": "RC-EF-3.0 142",
      "state": {
        "buttonevent": 4002,
        "lastupdated": "2021-04-19T22:09:25.875"
      },
      "swversion": "2019.9.10",
      "type": "ZHASwitch",
      "uniqueid": "ec:1b:bd:ff:fe:0f:a7:7d-01-0501"
    }
  }
}

From what I know there is no option for long press and double press. Just single press for alle 4 buttons. 

Here is some more info: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3828

It is compatible with home assistant.

**Comment by MadMonkey87** [comment]
Please check the beta over here: https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

**Comment by powermarcel10** [comment]
It is working! Thanks! Only one thing. The strange thing of this remote is that it sends out every command 4 times. Every 2 seconds it repeats the signal. I solved it by disabling the flow wich is used for a button after the flow run for the first time, and enable the flow after 15 seconds.. And that works..
However, is it something that you can fix in the driver maybe?
