### ISSUE TITLE
[FEATURE REQUEST] Addition of orentation information for Vibration sensor

### ISSUE THREAD

**Issue by mhoogenbosch** [MadMonkey87/HomeyCONZ#58]
Would it be possible to add the ‘orientation’ parameters to the aqara vibration sensor? They are available when pulling the rest api. 

  "9": {
    "config": {
      "battery": 98,
      "on": true,
      "pending": [],
      "reachable": true,
      "sensitivity": 11,
      "sensitivitymax": 21,
      "temperature": 3200
    },
    "ep": 1,
    "etag": "b8bf66597839bf06bce9c26741292c06",
    "lastseen": "2021-08-09T07:39Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.vibration.aq1",
    "name": "Vibration (kt)",
    "state": {
      "lastupdated": "2021-08-09T07:39:00.221",
      "orientation": [
        1,
        0,
        89
      ],
      "tiltangle": 74,
      "vibration": false,
      "vibrationstrength": 7
    },
    "swversion": "20180130",
    "type": "ZHAVibration",
    "uniqueid": "00:15:8d:00:02:af:d4:e8-01-0101"
  },

**Comment by MadMonkey87** [comment]
Yes I try to include this in the next release

**Comment by MadMonkey87** [comment]
Provided with 1.28.0, checkout the beta

**Comment by mhoogenbosch** [comment]
@MadMonkey87 .. wtf... it didn't work.. so finally got time to check this.

```
  "9": {
    "config": {
      "battery": 91,
      "on": true,
      "pending": [
        "sensitivity"
      ],
      "reachable": true,
      "sensitivity": 1,
      "sensitivitymax": 21,
      "temperature": 3100
    },
    "ep": 1,
    "etag": "bdec790565413c6bb310cd3de8d2caa9",
    "lastannounced": null,
    "lastseen": "2021-11-24T16:01Z",
    "manufacturername": "LUMI",
    "modelid": "lumi.vibration.aq1",
    "name": "Vibration (kt)",
    "state": {
      "lastupdated": "2021-11-24T16:02:56.003",
      "tiltangle": 10,
      "vibration": false,
      "vibrationstrength": 6
    },
    "swversion": "20180130",
    "type": "ZHAVibration",
    "uniqueid": "00:15:8d:00:02:af:d4:e8-01-0101"
  },
```

deConz completely removed the 'orientation' .. I'll open a case with them.
