### ISSUE TITLE
[BUG] Status indicators of Vibration sensor don't work 

### ISSUE THREAD

**Issue by mhoogenbosch** [MadMonkey87/HomeyCONZ#59]
Cannot select a indicator in the menu. Nor does it show a alert when the sensor is moving.

**Comment by MadMonkey87** [comment]
Can you please report this to Athom? This is actually nothing I can control from the app and as far as I know you can only set the indicator to one of the built in capabilities, but there is none available for the vibration alarm so I needed to implement it as custom capability. Also it seems that Athom has changed the alert behaviour with the introduction of custom indicators, again nothing I can change

**Comment by mhoogenbosch** [comment]
Have e-mailed support, i'll report back with their answer.

**Comment by mhoogenbosch** [comment]
Answer:

Hi Martijn,

Thank you for contacting Athom support! 

Your question seems to be developer-related and unfortunately we cannot give development support.

I am not sure how his app was created so at this moment there is also not much that I can do directly.

However you can point him the developer channels that we have to discuss these matter

— Homey Community Forum: https://community.athom.com/c/developers
— Homey Community Slack: https://slack.athom.com #developers

Or if this seems more like a bug, it can be reported here:

— Apps SDK: https://github.com/athombv/homey-apps-sdk-issues/issues
- Web API: https://github.com/athombv/homey-web-api-issues/issues
Best Regards,
Erik
The Athom support team.


---

So basically... no solution.
