### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Seinuh** [MadMonkey87/HomeyCONZ#6]
can't add Aqara Button..

**Comment by MadMonkey87** [comment]
Hey, could you please be a bit more specific? I.e what exactly happens, do you get an error message or could you post the log?

**Comment by Seinuh** [comment]
I can add it to my phoscon, but when i select it in homeyconz it doesn't find the device..

**Comment by MadMonkey87** [comment]
Can you please open this url in your browser and post here the result you get: http://[IP ADRESS]:[PORT]/api/[API KEY]/sensors

You need to replace the content in the brackets with the according setting in the app config

**Comment by Seinuh** [comment]
"manufacturername":"LUMI","mode":1,"modelid":"lumi.remote.b1acn01","name":"Keuken Schakerlaar","state":{"buttonevent":1002,"lastupdated":"2020-05-21T16:24:31"},"swversion":"20180525","type":"ZHASwitch","uniqueid":"00:15:8d:00:04:01:91:2c-01-0012"},"44":{"config":{"alert":"none","battery":100,"delay":0,"ledindication":false,"on":true,"pending":[],"reachable":true,"sensitivity":2,"sensitivitymax":4,"usertest":false},"ep":2,"etag":"37f7870684a905ded45758456e7d5883"

**Comment by MadMonkey87** [comment]
Seems to be a new model, i'll add it to the next version. 

Btw: if you are in a hurry you could also try to add it as a generic button😉

**Comment by Seinuh** [comment]
Thanks for your support 👍

**Comment by MadMonkey87** [comment]
Can you please install the beta of the next update over here: https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

could you please confirm that this now works?

**Comment by Seinuh** [comment]
Yes! It works 👍👍

**Comment by MadMonkey87** [comment]
Fixed with 1.5.0
