### ISSUE TITLE
[FEATURE REQUEST]: Generic Blinds:  Adding STOP function as Flow Card action

### ISSUE THREAD

**Issue by boldiebold** [MadMonkey87/HomeyCONZ#60]
**Is your feature request related to a problem? Please describe.**
I cannot stop the blinds with a  mapped button, just opening, closing or a concrete position. Stop function is not available as flow card action. Manually I can stop through the device

**Describe the solution you'd like**
Please add the stop function as flow card action, too 

![IMG_1758](https://user-images.githubusercontent.com/52777334/132089499-cdf05a1b-30af-4bf2-9b3d-83500447752f.jpeg)

![IMG_1756](https://user-images.githubusercontent.com/52777334/132089367-5f76eace-9d84-4506-95e6-1b7bff10ddfb.jpeg)

![IMG_1757](https://user-images.githubusercontent.com/52777334/132089353-16faf6a3-fccb-4604-8b21-325ed9b818c4.PNG)

**Comment by MadMonkey87** [comment]
Provided with 1.28.0, checkout the beta

**Comment by boldiebold** [comment]
I checked it with the actual beta 1.28.0.
Flow is not working. Will get error "http is not defined"

within the device tile stop is working fine

![Bildschirmfoto 2021-11-21 um 18 17 01](https://user-images.githubusercontent.com/52777334/142772261-5e93f3a5-414b-419a-afbe-8d9d00eb9fca.png)

**Comment by boldiebold** [comment]
In 1.29.0 still the same
