### ISSUE TITLE
[DEVICE REQUEST] Samsung Smartthings Motion Sensor

### ISSUE THREAD

**Issue by Tistrup** [MadMonkey87/HomeyCONZ#63]
If possible please add this so I can use it in Homey

There are also Samsung Smartthings Button and Samsung Smartthings Multipurpose Sensor

https://dresden-elektronik.github.io/deconz-rest-doc/devices/samsung/samjin_button_switch/
https://dresden-elektronik.github.io/deconz-rest-doc/devices/samsung/samjin_multi_sensor/

Should I create Device request for them or ?

**Device Name & Manufacturer**
They where made by Samsung, but now it is Aeotec that sell the unit

Samsung Smartthings Motion Sensor (but today they are called Aeotec Motion Sensor

**Device Description Link**
https://aeotec.com/smartthings/zigbee-motion-sensor.html

**Device state as reported by deConz**
Is this device a light or a sensor resource?
Sensor

sensor resource

{
    "config": {
        "battery": 81,
        "duration": 60,
        "enrolled": 1,
        "on": true,
        "pending": [],
        "reachable": true
    },
    "ep": 1,
    "etag": "96c49caaa32d54b9a4e06cf9dd1642d5",
    "lastannounced": "2021-09-25T02:10:08Z",
    "lastseen": "2021-09-25T05:02Z",
    "manufacturername": "Samjin",
    "modelid": "motion",
    "name": "Samsung Motion Sensor 1",
    "state": {
        "lastupdated": "2021-09-25T05:03:09.338",
        "lowbattery": false,
        "presence": true,
        "tampered": false
    },
    "type": "ZHAPresence",
    "uniqueid": "28:6d:97:00:01:11:7b:87-01-0500"
}

{
    "config": {
        "battery": 81,
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "582adb66fc1a0e21d01997e62d8043c4",
    "lastannounced": "2021-09-25T02:10:08Z",
    "lastseen": "2021-09-25T05:04Z",
    "manufacturername": "Samjin",
    "modelid": "motion",
    "name": "Samsung Motion Sensor 1",
    "state": {
        "lastupdated": "2021-09-25T05:02:17.982",
        "temperature": 2419
    },
    "type": "ZHATemperature",
    "uniqueid": "28:6d:97:00:01:11:7b:87-01-0402"
}

**Comment by MadMonkey87** [comment]
Will be supported in 1.29.x!
