### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iisworks** [MadMonkey87/HomeyCONZ#69]
On all my Tuya Blitzwolf smart plugs (model TS011F), the Current divider seems to be wrong; 100 instead of 1000 (value in api in mA).

Example (2.76A should be 0.276A):
![image](https://user-images.githubusercontent.com/33196233/143766455-7ec08009-c4ce-40ae-8ab8-7a4ca67e5629.png)

**Comment by MadMonkey87** [comment]
Will be fixed in 1.29.2
