### ISSUE TITLE
Could you please ad the smoke sensor from Trust 

### ISSUE THREAD

**Issue by goudhaan** [MadMonkey87/HomeyCONZ#7]
**Device name: Trust ZSDR-850 smoke sensor**

**Device link: https://www.klikaanklikuit.nl/nl/zigbee-smoke-detector.html**

**Device modelid:**

**Device capabilities:Smoke Alarm, Battery Alarm 
![C938AF39-BE10-447D-980C-C66650831F5E](https://user-images.githubusercontent.com/51194478/82546093-e387a880-9b57-11ea-8c08-ac1962557a55.png)
**

**State report example:**

**Comment by MadMonkey87** [comment]
Hi, could you please open http://[IP ADRESS]:[PORT]/api/[API KEY]/sensors & http://[IP ADRESS]:[PORT]/api/[API KEY]/lights in your browser and post the results here? You'll need to replace the content in brackets with the accoring setting of the app config

**Comment by goudhaan** [comment]
"manufacturername":"Heiman","modelid":"SMOK_V16","name":"Smoke Sensor","state":{"fire":false,"lastupdated":"none","lowbattery":false,"tampered":false},"swversion":"20150330","type":"ZHAFire","uniqueid":"00:50:43:c9:5f:21:45:2a-01-0500"},"5":{"config":{"battery":100,"group":"2634","on":true,"reachable":true},"ep":2,"etag":"837a1dad44dbe83a1e5a08e57df9efab"






Op 21 mei 2020 om 14:38 uur schreef Philippe Wechsler <notifications@github.com>:






Hi, could you please open http://[IP ADRESS]:[PORT]/api/[API KEY]/sensors & http://[IP ADRESS]:[PORT]/api/[API KEY]/lights in your browser and post the results here? You'll need to replace the content in brackets with the accoring setting of the app config

**Comment by MadMonkey87** [comment]
is there maybe an resource for the siren in the lights?

**Comment by goudhaan** [comment]
i have searched through the lights but can't find anything.
deleted the sensor again and added it as a light, but still no results.
this is what i got:


"manufacturername":"Heiman","modelid":"SMOK_V16","name":"Smoke Sensor","state":{"fire":false,"lastupdated":"2020-05-23T14:50:45","lowbattery":false,"tampered":false},"swversion":"20150330","type":"ZHAFire","uniqueid":"00:50:43:c9:5f:21:45:2a-01-0500"},"5":{"config":{"battery":100,"group":"2634","on":true,"reachable":true},"ep":2,"etag":"f0833a209120dce071226f3517329d20"
if i have to do something special please tell me, but as far as i can see this is it.

Op 23 mei 2020 om 15:53 uur schreef Philippe Wechsler <notifications@github.com>:






is there maybe an resource for the siren in the lights?

**Comment by MadMonkey87** [comment]
No problem, I can integrate it like that. Just one last question: is this really the trust sensor? Just because it seems to be the heiman one

**Comment by MadMonkey87** [comment]
An prerelease of the app with support for your sensor is available in the store: https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

Please test it and confirm if it works or not;)

**Comment by goudhaan** [comment]
Yes it works.
Thank you for your help. 

Met vriendelijke groeten,
With kind regards,

Jan Goudriaan

**Comment by goudhaan** [comment]
It works thank you. 
The only thing I can see that’s a bit weird is that I can at the smoke sensor in de deconz but it wil not appear in the phoscon app. 
But you can add it now in homey. 

Met vriendelijke groeten,
With kind regards,

Jan Goudriaan

**Comment by goudhaan** [comment]
You can also not change the name in deconz if you wanted to. Normally you would change the name in the phoscon app, but because it is not visible in phoscon app you can’t change it. For me not a issue but for others who not use deconz just the phoscon app to at the sensor it could be difficult. This because then you can not know when the sensor has successfully been added.

**Comment by goudhaan** [comment]
and the battery update seems to update not by itself. i can force it to by clicking the test button and read power discription.

**Comment by MadMonkey87** [comment]
This are all issues related to deconz itself and I suggest you to open an issue their repo.

Just one remark regaring the battery and homey: if you have added the device to homey it may take some time until you get the battery status displayed. Either until the battery level actually changes or up to 15 minutes where tha app automatically updates certain values.
