### ISSUE TITLE
hue tap

### ISSUE THREAD

**Issue by joelvanderkuur** [MadMonkey87/HomeyCONZ#8]
**Describe the bug:**
add request for the Philips Hue tap

**Comment by MadMonkey87** [comment]
Hi, could you please open http://[IP ADRESS]:[PORT]/api/[API KEY]/sensors & http://[IP ADRESS]:[PORT]/api/[API KEY]/lights in your browser and post the results here? You'll need to replace the content in brackets with the accoring setting of the app config

**Comment by joelvanderkuur** [comment]
this is what I get for the hue tap:
"manufacturername":"Philips","modelid":"ZGPSWITCH","name":"Tap","state":{"buttonevent":18,"lastupdated":"2020-05-23T07:11:13"},"type":"ZGPSwitch","uniqueid":"00:00:00:00:00:45:11:99-f2"},"14":{"config":{"battery":77,"group":"5","on":true,"reachable":true},"ep":2,"etag":"dd4f33c28f0b47dadb8125d432827b66",

**Comment by MadMonkey87** [comment]
An prerelease of the app with support for your sensor is available in the store: https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/

Please test it and confirm if it works or not;)

**Comment by joelvanderkuur** [comment]
it works! only get this tags see picture
![IMG_5958](https://user-images.githubusercontent.com/25392999/82834528-b45b9900-9ec1-11ea-9ce8-6108db8d86d6.PNG)

i don't know what this, 
button index = 16
action index = 2
event = 16
action = release_after_press

**Comment by MadMonkey87** [comment]
These tags are available for all switch events and can be used for advanced scenarios, see deconz spec. You can ignore them if you do not need them
