### ISSUE TITLE
The homey app stop working???  e20225c5-078b-47a9-a41e-97ae2be3046f

### ISSUE THREAD

**Issue by nissenhj** [MadMonkey87/HomeyCONZ#9]
**Describe the bug:**

**How to reproduce:**

**How it should work:**

**Screenshots:**

**Additional context:**

**Comment by MadMonkey87** [comment]
The log of your provided id is empty, so I guess the app did not really start. Can you please do the following:
1) install the latest beta from here (won't break anything on your setup and will be fully compatible with older and newer versions): https://homey.app/de-ch/app/de.dresden-elektronik.deconz/deCONZ/test/
2) if it still does not work restart the app and wait at least 15min!
3) if it still does not work please submit the log again
